var APIBuilder = require('@axway/api-builder-runtime');
var Model = APIBuilder.createModel('employeewages', {
    "connector": "composite",
    "fields": {
        "birth_date": {
            "type": "date",
            "model": "mysql/employees",
            "name": "birth_date"
        },
        "first_name": {
            "type": "string",
            "model": "mysql/employees",
            "name": "first_name"
        },
        "last_name": {
            "type": "string",
            "model": "mysql/employees",
            "name": "last_name"
        },
        "gender": {
            "type": "string",
            "model": "mysql/employees",
            "name": "gender"
        },
        "hire_date": {
            "type": "date",
            "model": "mysql/employees",
            "name": "hire_date"
        },
        "mysql/salaries": {
            "model": "mysql/salaries",
            "type": "array"
        }
    },
    "actions": [
        "read"
    ],
    "metadata": {
        "primarykey": "emp_no",
        "primaryKeyDetails": {
            "autogenerated": false,
            "type": "number"
        },
        "inner_join": [
            {
                "model": "mysql/salaries",
                "join_properties": {
                    "emp_no": "emp_no"
                }
            }
        ]
    }
});
module.exports = Model;